import { type FC } from 'react';
import { BookOpen } from 'lucide-react';

const UuidReference: FC = () => {
  return (
    <section
      id="specs-section"
      className="mx-auto w-full max-w-5xl rounded-3xl border border-slate-800/80 bg-slate-900/30 p-6 shadow-xl backdrop-blur-xl sm:p-8 lg:p-10"
    >
      <div className="flex items-center gap-2 border-b border-slate-800/80 pb-5">
        <BookOpen className="h-5 w-5 text-indigo-400" />
        <h2 className="text-xl font-bold tracking-tight text-white sm:text-2xl">UUID Standards & Specifications</h2>
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-2">
        {/* UUID v4 Card */}
        <div className="flex flex-col rounded-2xl border border-slate-800 bg-slate-950/60 p-5">
          <div className="flex items-center justify-between">
            <span className="font-mono text-sm font-bold text-indigo-400">UUID Version 4</span>
            <span className="rounded-full border border-indigo-500/20 bg-indigo-500/10 px-2.5 py-0.5 text-[11px] font-semibold text-indigo-300">
              RFC 4122 Standard
            </span>
          </div>

          <h3 className="mt-2 text-base font-bold text-white">Cryptographically Random</h3>
          <p className="mt-2 text-xs leading-relaxed text-slate-400">
            UUID v4 uses 122 bits of pseudo-random entropy generated by your system’s secure random number generator (
            <code className="text-slate-300">crypto.getRandomValues</code>). The odds of finding two duplicate v4 UUIDs
            is practically zero: you would need to generate 1 billion UUIDs every second for 85 years to have a 50%
            chance of a single collision.
          </p>

          <div className="border-slate-850 mt-4 space-y-1.5 border-t pt-3 font-mono text-[11px] text-slate-400">
            <div>• Total possible UUIDs: 5.3 × 10³⁶</div>
            <div>
              • Format: <span className="text-slate-300">xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx</span>
            </div>
          </div>
        </div>

        {/* UUID v7 Card */}
        <div className="flex flex-col rounded-2xl border border-slate-800 bg-slate-950/60 p-5">
          <div className="flex items-center justify-between">
            <span className="font-mono text-sm font-bold text-cyan-400">UUID Version 7</span>
            <span className="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-2.5 py-0.5 text-[11px] font-semibold text-cyan-300">
              RFC 9562 (New Standard)
            </span>
          </div>

          <h3 className="mt-2 text-base font-bold text-white">Unix Epoch Time-Ordered</h3>
          <p className="mt-2 text-xs leading-relaxed text-slate-400">
            UUID v7 embeds a 48-bit millisecond timestamp in the most significant bits followed by 74 random bits.
            Because values naturally increase over time, UUID v7 prevents B-Tree index fragmentation in databases like
            PostgreSQL, MySQL, and SQLite while preserving distributed generation capabilities.
          </p>

          <div className="border-slate-850 mt-4 space-y-1.5 border-t pt-3 font-mono text-[11px] text-slate-400">
            <div>• Database friendly: naturally clustered index</div>
            <div>• Extractable creation timestamp down to millisecond</div>
          </div>
        </div>
      </div>

      {/* Anatomy Visualizer */}
      <div className="mt-6 rounded-2xl border border-slate-800/80 bg-slate-950/80 p-5">
        <h3 className="text-sm font-bold text-slate-200">Anatomy of a Standard 128-Bit UUID</h3>
        <p className="mt-1 text-xs text-slate-400">
          A UUID is structured into 5 segments separated by hyphens (8-4-4-4-12 hex characters):
        </p>

        <div className="mt-4 overflow-x-auto">
          <div className="flex min-w-125 items-stretch gap-1.5 font-mono text-xs">
            <div className="flex-1 rounded-lg border border-indigo-500/30 bg-indigo-500/10 p-2.5 text-center">
              <div className="font-bold text-indigo-300">018f6f59</div>
              <div className="mt-1 text-[10px] text-slate-400">time_low (32 bits)</div>
            </div>
            <div className="w-24 rounded-lg border border-purple-500/30 bg-purple-500/10 p-2.5 text-center">
              <div className="font-bold text-purple-300">7f52</div>
              <div className="mt-1 text-[10px] text-slate-400">time_mid (16b)</div>
            </div>
            <div className="w-24 rounded-lg border border-cyan-500/30 bg-cyan-500/10 p-2.5 text-center">
              <div className="font-bold text-cyan-300">70b9</div>
              <div className="mt-1 text-[10px] text-slate-400">ver (4b) + time_hi</div>
            </div>
            <div className="w-24 rounded-lg border border-amber-500/30 bg-amber-500/10 p-2.5 text-center">
              <div className="font-bold text-amber-300">9e8c</div>
              <div className="mt-1 text-[10px] text-slate-400">variant + clock</div>
            </div>
            <div className="flex-1 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-2.5 text-center">
              <div className="font-bold text-emerald-300">8f92bd33e210</div>
              <div className="mt-1 text-[10px] text-slate-400">node / random entropy (48 bits)</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default UuidReference;
