import type { Metadata } from 'next'
import type { FC, ReactNode } from 'react'
import { Toaster } from 'sonner'

import Footer from '@/components/Footer'

import './globals.css'

export const metadata: Metadata = {
	title: 'Next UUID Generator',
	description: 'Generated by create next app'
}

type RootLayoutProps = Readonly<{
	children: ReactNode
}>

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang='en'>
			<body>
				{children}
				<Footer />
				<Toaster />
			</body>
		</html>
	)
}

export default RootLayout
